# Generated by Django 5.0.3 on 2024-04-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_status_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Panding'), ('cancelled', 'cancelled'), ('confirm', 'Confirm')], max_length=10),
        ),
    ]
