# Generated by Django 5.0.3 on 2024-04-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('delivered', 'Delivered'), ('confirem', 'Confirm'), ('on the way', 'On the way'), ('pending', 'Panding'), ('cancelled', 'Cancelled')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('cancelled', 'cancelled'), ('pending', 'Panding'), ('confirm', 'Confirm')], max_length=10),
        ),
    ]
