# Generated by Django 5.0.3 on 2024-04-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_order_status_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Panding'), ('on the way', 'On the way'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered'), ('confirem', 'Confirm')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('confirm', 'Confirm'), ('pending', 'Panding'), ('cancelled', 'cancelled')], max_length=10),
        ),
    ]
