# Generated by Django 5.0.3 on 2024-04-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_order_status_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='user_image',
            field=models.ImageField(default='static/user.png', upload_to='media/img/profile/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pin_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('cancelled', 'Cancelled'), ('on the way', 'On the way'), ('pending', 'Panding'), ('confirem', 'Confirm'), ('delivered', 'Delivered')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderbill',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderbill',
            name='pin_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderbill',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Panding'), ('confirm', 'Confirm'), ('cancelled', 'cancelled')], max_length=10),
        ),
    ]
